/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PayableIndexImport } from './routes/payable/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AssignorIndexImport } from './routes/assignor/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PayableIndexRoute = PayableIndexImport.update({
  id: '/payable/',
  path: '/payable/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AssignorIndexRoute = AssignorIndexImport.update({
  id: '/assignor/',
  path: '/assignor/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/assignor/': {
      id: '/assignor/'
      path: '/assignor'
      fullPath: '/assignor'
      preLoaderRoute: typeof AssignorIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/payable/': {
      id: '/payable/'
      path: '/payable'
      fullPath: '/payable'
      preLoaderRoute: typeof PayableIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/assignor': typeof AssignorIndexRoute
  '/login': typeof LoginIndexRoute
  '/payable': typeof PayableIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/assignor': typeof AssignorIndexRoute
  '/login': typeof LoginIndexRoute
  '/payable': typeof PayableIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/assignor/': typeof AssignorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/payable/': typeof PayableIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assignor' | '/login' | '/payable'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assignor' | '/login' | '/payable'
  id: '__root__' | '/' | '/assignor/' | '/login/' | '/payable/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AssignorIndexRoute: typeof AssignorIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PayableIndexRoute: typeof PayableIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AssignorIndexRoute: AssignorIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PayableIndexRoute: PayableIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/assignor/",
        "/login/",
        "/payable/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/assignor/": {
      "filePath": "assignor/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/payable/": {
      "filePath": "payable/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
